[package]
authors = ["Xuanwo <github@xuanwo.io>"]
categories = ["command-line-utilities"]
description = "Rust native client to hdfs"
documentation = "https://docs.rs/hdrs"
edition = "2021"
license = "Apache-2.0"
name = "hdrs"
repository = "https://github.com/Xuanwo/hdrs"
version = "0.3.2"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["hdfs-sys/hdfs_2_6"]
async_file = ["dep:futures", "dep:blocking"]
vendored = ["hdfs-sys/vendored"]
hdfs_2_6 = ["hdfs-sys/hdfs_2_6"]
hdfs_2_7 = ["hdfs-sys/hdfs_2_7"]
hdfs_2_8 = ["hdfs-sys/hdfs_2_8"]
hdfs_2_9 = ["hdfs-sys/hdfs_2_9"]
hdfs_2_10 = ["hdfs-sys/hdfs_2_10"]
hdfs_3_0 = ["hdfs-sys/hdfs_3_0"]
hdfs_3_1 = ["hdfs-sys/hdfs_3_1"]
hdfs_3_2 = ["hdfs-sys/hdfs_3_2"]
hdfs_3_3 = ["hdfs-sys/hdfs_3_3"]


[dependencies]
blocking = { version = "1.3.0", optional = true }
errno = "0.3"
futures = { version = "0.3", optional = true }
hdfs-sys = { git = "https://github.com/flarioncode/hdfs-sys.git", branch = "flarion", default-features = false }
libc = "0.2"
log = "0.4"

[dev-dependencies]
anyhow = "1"
dotenv = "0.15"
env_logger = "0.11"
futures = "0.3"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }
